import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainNavbar from "./components/MainNavbar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by Asif Ali",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Header */}
        <header style={{ padding: "1rem", background: "#e5e7eb" }}>
          <MainNavbar />
        </header>

        {/* Page content */}
        <main style={{ minHeight: "80vh", padding: "1rem" }}>{children}</main>

        {/* Footer */}
        <footer
          style={{
            padding: "1rem",
            background: "#e5e7eb",
            textAlign: "center",
          }}
        >
          © 2026 Asif Ali
        </footer>
      </body>
    </html>
  );
}
